@isTest
private class DummyTestClass {

	static testMethod void testSort() {
			ClassToBeDeleted delet = new ClassToBeDeleted();
			DummyClass dc = new DummyClass();
			DummyClass1 dc1 = new DummyClass1();
			DummyClass2 dc2 = new DummyClass2();
			DummyClass3 dc3 = new DummyClass3();
			DummyClass4 dc4 = new DummyClass4();
			DummyClass5 dc5 = new DummyClass5();
			DummyClass6 dc6 = new DummyClass6();
			DummyClass7 dc7 = new DummyClass7();
	}

}
